server:
  port: 8080
  error:
    include-stacktrace: ON_PARAM
spring:
  application:
    name: pdv
  datasource:
    url: jdbc:mysql://localhost:3306/pdv?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: leonan2knet
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



